package:
  name: waves
  # TODO: Figure out how to use pyproject.toml or setup.py and a Conda build Jinja template
  version: {{ VERSION }}

source:
  path: '..'

build:
  noarch: python
  entry_points:
    - parameter_study = waves.parameter_study:main
  script:
    # TODO: figure out how to use the setuptools recommended pyproject.toml and 'build' package and stop using the
    # deprecated setup.py solutions
    - python setup.py install
    # TODO: install shell scripts from pyproject.toml if possible
    - cp waves/bin/* ${PREFIX}/bin
  script_env:
    - VERSION
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python >=3.8
    - git
    - setuptools
    - setuptools_scm
  host:
    - python >=3.8
    - setuptools
    - setuptools_scm
  run:
    - python >=3.8
    - pyyaml
    - scons

test:
  requires:
    - pytest
    - pytest-xdist
    - pyyaml
    - scons
    - setuptools_scm
  source_files:
    - SConstruct
    - SConscript
    - README.rst
    - waves/SConscript
    - waves/pytest.ini
    - waves/tests/*.py
    - eabm/
  imports:
    - waves
  commands:
    # TODO: Test from the as installed directory where possible, e.g. waves pytests
    - scons . --keep-going conditional_ignore=False ignore_documentation=True
    # Test the SCons-EABM targets and tests
    - cd eabm && scons . --keep-going conditional_ignore=False ignore_documentation=True
