package:
  name: waves
  # TODO: Figure out how to use pyproject.toml or setup.py and a Conda build Jinja template
  version: {{ VERSION }}

source:
  path: '..'

build:
  noarch: python
  script:
    # TODO: figure out how to use the setuptools recommended pyproject.toml and 'build' package and stop using the
    # deprecated setup.py solutions
    - {{ PYTHON }} setup.py install
    # TODO: install shell scripts from pyproject.toml if possible
    - cp waves/bin/* ${PREFIX}/bin
  script_env:
    - VERSION
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python {{ python }}
    - git
    - setuptools
    - setuptools_scm
  host:
    - python
    - setuptools
    - setuptools_scm
  run:
    - python >=3.8
    - pyyaml
    - scons

test:
  requires:
    - pytest
    - pytest-xdist
    - pyyaml
    - scons
    - setuptools_scm
  source_files:
    # Everything copied here will make it into the "info" directory of the Conda package
    - SConstruct
    - SConscript
    - README.rst
    - waves/SConscript
    - waves/pytest.ini
    - waves/tests/*.py
    - eabm/README.rst
    - eabm/SC*
    - eabm/source/abaqus/*
    - eabm/source/cubit/*
    - eabm/source/python/*
    - eabm/tutorial*/*
  imports:
    - waves
  commands:
    - scons . --keep-going conditional_ignore=False ignore_documentation=True
    - cd eabm && scons . --keep-going conditional_ignore=False ignore_documentation=True --jobs=4
