package:
  name: waves
  # TODO: Figure out how to use pyproject.toml or setup.py and a Conda build Jinja template
  version: {{ VERSION }}

source:
  path: '..'

build:
  noarch: python
  script:
    # Build package documentation to bundle in Conda package
    - scons man html
    - manpath1="$PREFIX/share/man/man1"
    - manpath2="$PREFIX/man/man1"
    - mkdir -p $manpath1 $manpath2
    - cp build/docs/man/waves.1 $manpath1
    - cp build/docs/man/waves.1 $manpath2 || true
    # Copy the shell scripts and any other non-Python executables to PATH/bin
    - environment_bin=${PREFIX}/bin
    - mkdir -p ${environment_bin}
    - cp waves/bin/waves_build_wrapper ${environment_bin}
    # Build and install Conda package
    # TODO: figure out how to use the setuptools recommended pyproject.toml and 'build' package and stop using the
    # deprecated setup.py solutions
    - {{ PYTHON }} setup.py install
    # Bundle HTML documentation. Must come after install so that SP_DIR path exists
    - docspath="$SP_DIR/$PKG_NAME/docs"
    - mkdir -p $docspath
    - cp -r build/docs/html/* $docspath
  script_env:
    - VERSION
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python {{ python }}
    - git
    - scons >=4
    - setuptools
    - setuptools_scm
    - sphinx >=3,<5
    - sphinx-argparse
    - sphinx_rtd_theme >=0.5
    - sphinxcontrib-bibtex
  host:
    - python
    - setuptools
    - setuptools_scm
  run:
    - python >=3.8
    - h5netcdf
    - h5py
    - numpy
    - pandas
    - pyyaml
    - scipy
    - scons
    - smt
    - xarray

test:
  requires:
    - h5netcdf
    - h5py
    - numpy
    - pytest
    - pytest-xdist
    - pyyaml
    - scipy
    - scons
    - setuptools_scm
    - smt
    - xarray
  source_files:
    # Everything copied here will make it into the "info" directory of the Conda package
    - SConstruct
    - SConscript
    - README.rst
    - waves/SConscript
    - waves/pytest.ini
    - waves/tests/*.py
    - eabm/README.rst
    - eabm/SC*
    - eabm/*SConstruct
    - eabm/eabm_package/abaqus/*
    - eabm/eabm_package/cubit/*
    - eabm/eabm_package/python/*
    - eabm/tutorial*/*
  imports:
    - waves
  commands:
    - scons . --keep-going --unconditional-build --ignore-documentation
    - cd eabm
    # Regression test the files used in the tutorial documentation
    - scons . --sconstruct=scons_quickstart_SConstruct --keep-going
    - scons . --sconstruct=waves_quickstart_SConstruct --keep-going
    - scons . --sconstruct=tutorial_00_SConstruct --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_01_geometry_SConstruct --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_02_partition_mesh_SConstruct --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_03_solverprep_SConstruct --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_04_simulation_SConstruct --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_cubit_SConstruct --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_05_parameter_substitution_SConstruct --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_06_include_files_SConstruct --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_07_cartesian_product_SConstruct --jobs=4 --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_08_data_extraction_SConstruct --jobs=4 --keep-going --unconditional-build
    # Re-run the full WAVES-EABM suite once more with the full, advanced project definition in SContruct.
    # Uses "rm" instead of "scons --clean" to ensure a complete re-build even if the tutorial files and the default
    # SConstruct file target definitions differ or something is incompletely cleaned.
    - rm -rf build/
    - scons . --jobs=4 --keep-going --unconditional-build --ignore-documentation
