{% set data = load_setup_py_data() %}

package:
  name: waves
  version: {{ data.get('version') }}

source:
  path: '..'

build:
  script:
    - {{ PYTHON }} setup.py install
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python {{ python }}
    - git
    - build
    - setuptools
    - setuptools_scm
  host:
    - python
    - build
    - setuptools
    - setuptools_scm
  run:
    - python
    - pyyaml
    - scons

test:
  requires:
    - pytest
    - pytest-xdist
    - scons
    - setuptools_scm
  source_files:
    - SConstruct
    - SConscript
    - README.rst
    - waves/pytest.ini
    - waves/tests/*.py
    - eabm/
  imports:
    - waves
  commands:
    # TODO: package these files
    - cp SConstruct SConscript README.rst ${SP_DIR}/waves
    - cp waves/SConscript ${SP_DIR}/waves
    - cp docs/SConscript ${SP_DIR}/waves/docs
    - cp eabm/docs/SConscript ${SP_DIR}/waves/eabm/docs
    - cp eabm/SConstruct ${SP_DIR}/waves/eabm
    - cp eabm/SConscript ${SP_DIR}/waves/eabm
    - cp eabm/tutorial_01_geometry/SConscript ${SP_DIR}/waves/eabm/tutorial_01_geometry
    - cp eabm/tutorial_02_partition_mesh/SConscript ${SP_DIR}/waves/eabm/tutorial_02_partition_mesh
    - cp eabm/tutorial_03_solverprep/SConscript ${SP_DIR}/waves/eabm/tutorial_03_solverprep
    - cp eabm/tutorial_04_simulation/SConscript ${SP_DIR}/waves/eabm/tutorial_04_simulation
    # Test the Python package as installed in the environment
    - cd ${SP_DIR}/waves
    - scons
    # Test the EABM stub CMake targets and tests
    - cd eabm
    - scons
