package:
  name: waves
  version: {{ VERSION }}

source:
  path: '..'

build:
  script:
    - {{ PYTHON }} -m build 
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python {{ python }}
    - git
    - build
    - setuptools
    - setuptools_scm
  host:
    - python
    - setuptools
    - setuptools_scm
  run:
    - python
    - pyyaml
    - scons 

test:
  requires:
    - pytest
    - pytest-xdist
    - scons
  source_files:
    - waves/pytest.ini
    - waves/tests/*.py
    - eabm/
  imports:
    - waves
  commands:
    # Test the Python package as installed in the environment
    - cd ${SP_DIR}/waves
    - scons
    # Test the EABM stub CMake targets and tests
    - cd eabm 
    - scons
