{% set data = load_setup_py_data() %}

package:
  name: waves
  version: {{ data.get('version') }}

source:
  path: '..'

build:
  script:
    - {{ PYTHON }} setup.py install
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python {{ python }}
    - git
    - build
    - setuptools
    - setuptools_scm
  host:
    - python
    - build
    - setuptools
    - setuptools_scm
  run:
    - python
    - pyyaml
    - scons

test:
  requires:
    - pytest
    - pytest-xdist
    - pyyaml
    - scons
    - setuptools_scm
    - sphinx
    - sphinx-argparse
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex
  source_files:
    - SConstruct
    - SConscript
    - README.rst
    - waves/pytest.ini
    - waves/tests/*.py
    - eabm/
  imports:
    - waves
  commands:
    # TODO: Test from the as installed directory where possible, e.g. waves pytests
    - scons
    # Test the EABM stub CMake targets and tests
    - cd eabm
    - scons
