workflow:
  rules:  # Do not create pipelines for tag updates
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

include: ".pipeline-common.yml"

stages:
  - child-pipelines
  - scheduled

aea:
  stage: child-pipelines
  trigger:
    include:
      - local: .pipeline-aea.yml
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

hpc:
  stage: child-pipelines
  trigger:
    include:
      - local: .pipeline-hpc.yml
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

win:
  stage: child-pipelines
  trigger:
    include:
      - local: .pipeline-win.yml
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

deploy:
  stage: child-pipelines
  trigger:
    include:
      - local: .pipeline-deploy.yml
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == "main"

conda-build-matrix:
  extends:
    - .linux_before_script
  timeout: 4h
  stage: scheduled
  variables:
    GIT_STRATEGY: clone
  dependencies: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    # Set the LANL internal proxies
    - export ALL_PROXY="proxyout.lanl.gov:8080"
    - export HTTP_PROXY="http://$ALL_PROXY"
    - export HTTPS_PROXY=$HTTP_PROXY
    # Override default permissions. Set group to rx with no write permissions.
    - umask 0022
    - mkdir ${conda_artifacts_directory}
    - pytest recipe-matrix/matrix.py -v --no-showlocals --tb=short
    - conda build purge --croot ${croot}/recipe-matrix
  tags:
    - shell-aea
