workflow:
  rules:  # Do not create pipelines for tag updates
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

stages:
  - child-pipelines

aea:
  stage: child-pipelines
  trigger:
    include:
      - local: .pipeline-aea.yml
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

deploy:
  stage: child-pipelines
  trigger:
    include:
      - local: .pipeline-deploy.yml
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
