# Required for HPC Jacamar Runner
default:
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://re-git.lanl.gov

stages:
  - test

include: ".pipeline-common.yml"

fast-test:
  before_script:
    - (& "C:\ProgramData\anaconda3\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | ?{$_} | Invoke-Expression
    - conda env create --name waves-dev --file environment-win.yml --yes
    - conda activate waves-dev
  extends:
    - .fast-test
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
  tags:
    - powershell-aea
