stages:
  - test

include: ".pipeline-common.yml"

before_script:
  - $PSVersionTable
  # Common job variables
  - $conda_installation="C:\ProgramData\anaconda3"
  - $conda_environments="$conda_installation\envs"
  - $prefix=python -c 'import tempfile; print(tempfile.mkdtemp(prefix=r"C:\ProgramData\anaconda3\envs\waves-dev-"))'
  - Set-Content -Path prefix.txt -Value $prefix
  - $conda_artifacts_directory="conda-bld"
  - Write-Output $conda_installation
  - Write-Output $conda_environments
  - Write-Output $prefix
  - Write-Output $conda_artifacts_directory
  - if (!(Test-Path -Path $conda_installation -PathType Container)) { exit 1 }
  - if (!(Test-Path -Path $conda_environments -PathType Container)) { exit 1 }
  - if ([string]::IsNullOrEmpty($prefix)) { exit 1 }
  - if ([string]::IsNullOrEmpty($conda_artifacts_directory)) { exit 1 }
  # Environment creation
  - (& "$conda_installation\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | ?{$_} | Invoke-Expression
  - conda env create --prefix $prefix --file environment-win.yml --yes
  - conda activate $prefix
  # Common job variables
  - $croot="$CONDA_PREFIX\$conda_artifacts_directory"
  - Write-Output $croot
  - if ([string]::IsNullOrEmpty($croot)) { exit 1 }

after_script:
  - $prefix=Get-Content -Path prefix.txt
  - Write-Output $prefix
  - if ([string]::IsNullOrEmpty($prefix)) { exit 1 }
  - if (Test-Path -Path $prefix -PathType Container) {Remove-Item -Recurse $prefix -ErrorAction Continue}

win-fast-test:
  extends:
    - .fast-test-no-third-party
  stage: test
  rules:
    - if: $PARENT_CI_PIPELINE_SOURCE == "schedule"
    - if: $PARENT_CI_PIPELINE_SOURCE == "merge_request_event"
  tags:
    - powershell-aea
