# Required for HPC Jacamar Runner
default:
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://re-git.lanl.gov

stages:
  - test

include: ".pipeline-common.yml"

fast-test:
  before_script:
    - (& "C:\ProgramData\anaconda3\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | ?{$_} | Invoke-Expression
    - conda config --set proxy_servers.http http://proxyout.lanl.gov:8080
    - conda config --set proxy_servers.https http://proxyout.lanl.gov:8080
    - conda env create --name waves-dev --file environment-win.yml --yes
    - conda activate waves-dev
  after_script:
    - conda config --remove proxy_servers.http http://proxyout.lanl.gov:8080
    - conda config --remove proxy_servers.https http://proxyout.lanl.gov:8080
  extends:
    - .fast-test
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
  tags:
    - powershell-aea
