stages:
  - test

include: ".pipeline-common.yml"

win-fast-test:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
  tags:
    - powershell-aea
  variables:
    GIT_STRATEGY: clone
  script:
    # Environment creation/setup. Usually a ``before_script``.
    - $conda_installation="C:\ProgramData\anaconda3"
    - $conda_environments="$conda_installation\envs"
    - $prefix=python -c 'import tempfile; print(tempfile.mkdtemp(prefix=r"C:\ProgramData\anaconda3\envs\waves-dev-"))'
    - (& "$conda_installation\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | ?{$_} | Invoke-Expression
    - conda config --set proxy_servers.http http://proxyout.lanl.gov:8080
    - conda config --set proxy_servers.https http://proxyout.lanl.gov:8080
    - conda env create --prefix $prefix --file environment-win.yml --yes
    - conda activate $prefix
    # Tests
    - scons regression --keep-going --cov-report
    # Cleanup. Usually an ``after_script``
    - conda deactivate
    - conda env remove --prefix $prefix --yes
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/pytest/coverage.xml
