stages:
  - test

include: ".pipeline-common.yml"

mac-fast-test:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
  tags:
    - macos
    - pn2301275
  variables:
    GIT_STRATEGY: clone
  script:
    # Environment creation/setup. Usually a ``before_script``.
    - source $HOME/anaconda3/etc/profile.d/conda.sh
    - conda env create --name waves-dev --file environment.yml --yes
    - conda activate waves-dev
    # Tests
    - scons html html-internal flake8 pytest systemtest --cov-report
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/pytest/coverage.xml
