stages:
  - environment
  - test

include: ".pipeline-common.yml"

aea-environment:
  extends:
    - .linux_before_script
    - .environment
  stage: environment
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
  tags:
    - shell-aea

aea-fast-test:
  extends:
    - .linux_before_script
    - .fast-test
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
  tags:
    - shell-aea

aea-style-guide:
  extends:
    - .linux_before_script
    - .style-guide
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
  tags:
    - shell-aea

aea-conda-build:
  extends:
    - .linux_before_script
    - .conda-build
  stage: test
  dependencies: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
  tags:
    - shell-aea

aea-conda-build-external:
  extends:
    - .linux_before_script
  stage: test
  variables:
    GIT_STRATEGY: clone
  dependencies: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
  script:
    # Set the LANL internal proxies
    - export ALL_PROXY="proxyout.lanl.gov:8080"
    - export HTTP_PROXY="http://$ALL_PROXY"
    - export HTTPS_PROXY=$HTTP_PROXY
    # Override default permissions. Set group to rx with no write permissions.
    - umask 0022
    - mkdir ${conda_artifacts_directory}
    - VERSION=$(python -m setuptools_scm) conda mambabuild recipe --channel fierromechanics --channel conda-forge --no-anaconda-upload --croot ${croot}/recipe-external --output-folder ${conda_artifacts_directory}
    - conda build purge --croot ${croot}/recipe-external
  tags:
    - shell-aea
