stages:
  - test

include: ".pipeline-common.yml"

mac-fast-test:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
  tags:
    - macos
    - pn2301275
  variables:
    GIT_STRATEGY: clone
  script:
    # Environment creation/setup. Usually a ``before_script``.
    - conda_installation="${HOME}/anaconda3"
    - conda_environments="${conda_installation}/envs"
    - prefix=$(mktemp --directory --tmpdir=${conda_environments} waves-dev-XXXXXX)
    - echo ${conda_installation}
    - echo ${conda_environments}
    - echo ${prefix}
    - source ${conda_installation}/etc/profile.d/conda.sh
    - conda env create --prefix ${prefix} --file environment.yml --yes
    - conda activate ${prefix}
    # Tests
    - scons regression --keep-going --cov-report
    # Cleanup. Usually an ``after_script``
    - conda deactivate
    - conda env remove --prefix ${prefix} --yes
    - rm -r ${prefix} || true
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/pytest/coverage.xml
