.linux_before_script: &linux_before_script
  before_script:
    # Handle mixed AEA/HPC jobs
    - aea_compute_path="/projects/aea_compute"
    - scratch_path="/scratch/${USER}"
    - ci_environment_path="${aea_compute_path}"
    - hostname=$(hostname -f)
    - |
       if [[ ${hostname} == *.localdomain ]] || [[ ${hostname} == ??-rfe?.lanl.gov ]] || [[ ${hostname} == ??-fe?.lanl.gov ]]  || [[ "$hostname" == nid[0-9]* ]]; then
           aea_compute_path="/usr/projects/ea/aea_compute";
           scratch_path="/lustre/roscratch1/${USER}";
           ci_environment_path=${scratch_path};
       fi
    - echo ${aea_compute_path}
    - echo ${scratch_path}
    - echo ${ci_environment_path}
    - if [[ ! -d ${aea_compute_path} ]]; then exit 1; fi
    - if [[ ! -d ${scratch_path} ]]; then exit 1; fi
    - if [[ ! -d ${ci_environment_path} ]]; then exit 1; fi
    # Prep module command and load system module(s)
    - aea_modulefiles="${aea_compute_path}/modulefiles"
    - module use ${aea_modulefiles}
    - module load texlive
    # Start with an AEA environment to put Conda on PATH
    - environment_choices="aea-nightly aea-quarterly aea-release"
    - for env in ${environment_choices}; do if [[ -d "${aea_compute_path}/${env}" ]]; then base_environment=${env}; break; fi; done
    - echo ${base_environment}
    - if [[ -z ${base_environment} ]]; then exit 1; fi
    - module load ${base_environment}
    # Activate CI environment if available. If not, rely on environment job running before other jobs.
    - module use ${PWD}/modulefiles
    - project_environment='waves-env'
    - environment_path="${ci_environment_path}/${project_environment}"
    - echo ${environment_path}
    - if [[ -d ${environment_path} ]]; then module unload ${base_environment}; module load ${project_environment}; fi
    - conda info
    - conda_artifacts_directory='conda-bld'
    - croot="${scratch_path}/$(basename $PWD)/${conda_artifacts_directory}"

.environment: &environment
  variables:
    GIT_STRATEGY: clone
  script:
    # Always build from the base/aea compute environment with boa/libmamba
    - module unload ${project_environment}
    - module load ${base_environment}
    # Don't rebuild environment for merge request pipelines unless the environment is missing
    - if [[ -d "${environment_path}" ]]; then exists=true; else exists=false; fi
    - if [[ $CI_MERGE_REQUEST_ID ]] && ${exists}; then exit 0; fi
    # Don't rebuild environment for main unless the environment file has changed or the environment doesn't exist
    - files=$(git diff --name-only ${CI_COMMIT_SHA} ${CI_COMMIT_BEFORE_SHA}) || true
    - if [[ $CI_COMMIT_BRANCH == "main" ]]; then production=true; else production=false; fi
    - if [[ "${files}" == *"environment.yml"* ]]; then modified=true; else modified=false; fi
    - if ${production} && ${exists} && ! ${modified}; then exit 0; fi
    # Set LANL proxies
    - export ALL_PROXY="proxyout.lanl.gov:8080"
    - export HTTP_PROXY="http://$ALL_PROXY"
    - export HTTPS_PROXY=$HTTP_PROXY
    # Re-build the Conda environment on changes to environment files
    - conda env create --prefix ${environment_path} --file environment.yml --solver=libmamba --force
    # Remove write permissions from group to avoid accidental environment changes
    - chmod -R 755 ${environment_path}
    # place the common modulefiles in an accessible location
    - cp ${PWD}/modulefiles/* ${aea_modulefiles}
    # Link SCons man pages to the expected MANPATH location
    - ln ${environment_path}/scons.1 ${environment_path}/man/man1/scons.1 || true
    - ln ${environment_path}/sconsign.1 ${environment_path}/man/man1/sconsign.1 || true
    - ln ${environment_path}/scons-time.1 ${environment_path}/man/man1/scons-time.1 || true

.fast-test: &fast-test
  variables:
    GIT_STRATEGY: clone
  script:
    - scons regression --keep-going --unconditional-build --cov-report
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/pytest/coverage.xml

.style-guide: &style-guide
  variables:
    GIT_STRATEGY: clone
  script:
    - scons flake8 black-check

.conda-build: &conda-build
  variables:
    GIT_STRATEGY: clone
  script:
    # Set the LANL internal proxies
    - export ALL_PROXY="proxyout.lanl.gov:8080"
    - export HTTP_PROXY="http://$ALL_PROXY"
    - export HTTPS_PROXY=$HTTP_PROXY
    # Override default permissions. Set group to rx with no write permissions.
    - umask 0022
    - mkdir ${conda_artifacts_directory}
    - VERSION=$(python -m setuptools_scm) conda mambabuild recipe-internal --channel fierromechanics --channel conda-forge --no-anaconda-upload --croot ${croot}/recipe-internal --output-folder ${conda_artifacts_directory}
    - conda build purge --croot ${croot}/recipe-internal
  artifacts:
    expire_in: '2 hrs'
    paths:
      - conda-bld/noarch/waves-*-*.tar.bz2
