channels:
  - conda-forge

dependencies:
  - git
  - h5netcdf
  - h5py
  - mamba
  - matplotlib
  - networkx
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-xdist
  - pyyaml
  - salib >=1
  - scipy >=1
  - scons >=4
  - seaborn
  - sed
  - setuptools >=45
  - setuptools_scm[toml] >=6.2
  - sphinx >=5.1
  - sphinx-argparse
  - sphinx_rtd_theme >=1
  - sphinxcontrib-bibtex
  - xarray
  - pip:
    - sphinx-copybutton
