channels:
  - conda-forge

dependencies:
  - boa
  # TODO: Remove when conda-build 24.? no longer breaks boa/mambabuild
  - conda-build ==3.28
  - h5netcdf
  - h5py
  - ipython
  - matplotlib-base
  - networkx
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-cov
  - pytest-xdist
  - python-build
  - pyyaml
  - salib >=1
  - scipy >=1
  - scons >=4
  - seaborn
  - setuptools >=62
  - setuptools_scm[toml] >=6.2,<8
  - sphinx >=5.1
  - sphinx-argparse
  - sphinx-copybutton >=0.5.1
  - sphinx_rtd_theme >=1
  - sphinxcontrib-bibtex
  - xarray
