channels:
  - fierromechanics
  - conda-forge

dependencies:
  - boa
  - fierro-cpu
  - flake8
  - h5netcdf
  - h5py
  - ipython
  - lazy_loader >=0.4
  - matplotlib-base
  - mypy
  - networkx
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-cov
  - pytest-xdist
  - python-build
  - pyyaml
  - salib >=1
  - scipy >=1
  - scons >=4
  - seaborn
  - setuptools >=62
  - setuptools_scm[toml] >=6.2
  - sphinx >=5.1
  - sphinx-argparse
  - sphinx-copybutton >=0.5.1
  - sphinx_rtd_theme >=1
  - sphinxcontrib-bibtex
  - xarray
