[build-system]
requires = ["setuptools>=62", "setuptools_scm[toml]>=6.2,<8"]
build-backend = "setuptools.build_meta"

[project]
name = "waves"
authors = [
    {name = "Kyle Brindley", email = "kbrindley@lanl.gov"},
    {name = "Prabhu Khalsa", email = "pkhalsa@lanl.gov"},
    {name = "Thomas Roberts", email = "tproberts@lanl.gov"},
    {name = "Sergio Cordova", email = "sergioc@lanl.gov"},
    {name = "Matthew Fister", email = "mwfister@lanl.gov"},
    {name = "Scott Ouellette", email = "souellette@lanl.gov"}
]
description = "WAVES Analysis for Verified Engineering Simulations"
readme = "README.rst"
requires-python = ">=3.8"
license = {text = "BSD-3-Clause"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering"
]
dynamic = ["version"]
dependencies = [
    "h5netcdf",
    "h5py",
    "matplotlib-base",
    "networkx",
    "numpy",
    "pyyaml",
    "salib >=1",
    "scipy >=1.7",
    "scons",
    "xarray"
]

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
odb_extract = "waves.abaqus.odb_extract:main"
msg_parse = "waves.abaqus.msg_parse:main"
sta_parse = "waves.abaqus.sta_parse:main"
waves = "waves.main:main"

[project.urls]
homepage = "https://github.com/lanl/waves"
documentation = "https://github.com/lanl/waves"
repository = "https://github.com/lanl/waves"
changelog = "https://lanl.github.io/waves/changelog.html"

[tool.setuptools_scm]
write_to = "waves/_version.py"

[tool.pytest.ini_options]
markers = [
    "unittest: marks codebase unit tests",
    "integrationtest: marks integration tests",
    "systemtest: marks system tests, e.g. the tutorials",
    # FIXME: Trace the source of interference between the builder tests and the find_program tests
    # Remove tag and use of tag when fixed.
    "programoperations: marks tests that don't play nicely with SCons internal API usage"
]
addopts = "--ignore-glob='*modsim_template*' --ignore-glob='*tutorials*' --tb=long --showlocals --failed-first --strict-markers -n 4 -m 'not systemtest'"
