[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "WAVES"
description = "WAVES Analysis for Validated Engineering Simulations"
readme = "README.rst"
classifiers = ["Programming Language:: Python :: 3"]
dynamic = ["version"]

[tool.setuptools]
packages = ["waves"]

[project.scripts]
parameter_study = "waves.parameter_study:main"
odb_extract = "waves.abaqus:odb_extract"
msg_parse = "waves.abaqus.msg_parse:main"
sta_parse = "waves.abaqus.sta_parse:main"

[tool.setuptools_scm]
write_to = "waves/_version.py"
