package:
  name: waves
  # TODO: Figure out how to use pyproject.toml or setup.py and a Conda build Jinja template
  version: {{ VERSION }}

about:
  home: https://github.com/lanl/waves
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: WAVES (LANL code C23004) is a computational engineering workflow tool that integrates parametric studies with traditional software build systems.

source:
  path: '..'

build:
  noarch: python
  script:
    # Build package documentation to bundle in Conda package
    - scons man html-github
    - manpath1="$PREFIX/share/man/man1"
    - manpath2="$PREFIX/man/man1"
    - mkdir -p $manpath1 $manpath2
    - cp build/docs/man/waves.1 $manpath1
    - cp build/docs/man/waves.1 $manpath2 || true
    # Build and install Conda package
    # TODO: figure out how to use the setuptools recommended pyproject.toml and 'build' package and stop using the
    # deprecated setup.py solutions
    - {{ PYTHON }} setup.py install
    # Bundle HTML documentation. Must come after install so that SP_DIR path exists
    - docspath="$SP_DIR/$PKG_NAME/docs"
    - mkdir -p $docspath
    - cp -r build/docs/html-github/* $docspath
    # Bundle quickstart files. Must come after install so that SP_DIR path exists
    - quickstart_path="$SP_DIR/$PKG_NAME/quickstart"
    - mkdir -p ${quickstart_path}
    - cp -r --dereference quickstart/* ${quickstart_path}
  script_env:
    - VERSION
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python {{ python }}
    - git
    - scons >=4
    - setuptools >=45
    - setuptools_scm[toml] >=6.2
    - sphinx >=5.1
    - sphinx-argparse
    - sphinx_rtd_theme >=1
    - sphinxcontrib-bibtex
  host:
    - python
    - setuptools >=45
    - setuptools_scm[toml] >=6.2
  run:
    - python >=3.8
    - h5netcdf
    - h5py
    - numpy
    - pyyaml
    - salib >=1
    - scipy >=1.7
    - scons
    # TODO: Remove after updating minimum scipy requirement
    # https://re-git.lanl.gov/aea/python-projects/waves/-/issues/278
    - setuptools
    - xarray

test:
  requires:
    - pytest
    - pytest-xdist
  imports:
    - waves
  commands:
    - test_root=${PWD}
    # Tests that depend on correct install path
    - waves docs --print-local-path
    # Project unit tests
    - cd $SP_DIR/$PKG_NAME
    - pytest
