package:
  name: waves
  # TODO: Figure out how to use pyproject.toml and a Conda build Jinja template
  version: {{ VERSION }}

about:
  home: https://re-git.lanl.gov/aea/python-projects/waves
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Parameteric study computational engineering workflow tool'
  description: |
    WAVES (LANL code C23004) is a computational engineering workflow tool that integrates parametric studies with
    traditional software build systems.
  doc_url: https://aea.re-pages.lanl.gov/python-projects/waves/main/index.html
  dev_url: https://re-git.lanl.gov/aea/python-projects/waves

source:
  path: '..'

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ VERSION }}
  script:
    # Build and install Conda package
    - $PYTHON -m build --no-isolation
    - $PYTHON -m pip install dist/$PKG_NAME-$PKG_VERSION.tar.gz --no-deps --ignore-installed -v --no-build-isolation
    - $PYTHON -m pip show $PKG_NAME
    # Build man page and HTML documentation to bundle in Conda package
    - scons man html-internal
    - $PYTHON package_documentation.py
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - scons >=4
    - sphinx >=5.1
    - sphinx-argparse
    - sphinx-copybutton >=0.5.1
    - sphinx_rtd_theme >=1
    - sphinxcontrib-bibtex
  host:
    - python
    - python-build
    - pip
    - setuptools >=45
    - setuptools_scm[toml] >=6.2
  run:
    - python >=3.8
    - h5netcdf
    - h5py
    - matplotlib-base
    - networkx
    - numpy
    - pyyaml
    - salib >=1
    - scipy >=1.7
    - scons
    - xarray

test:
  requires:
    - h5netcdf
    - h5py
    - matplotlib-base
    - numpy
    - pandas
    - pytest
    - pytest-xdist
    - pyyaml
    - salib >=1
    - scipy >=1.7
    - scons
    - seaborn
    - sed
    - setuptools_scm
    - xarray
  imports:
    - waves
  commands:
    - test_root=${PWD}
    # Tests that depend on correct install path
    - waves docs --print-local-path
    # Test as-installed project unit tests
    - cd $SP_DIR/$PKG_NAME
    # FIXME: Trace the source of interference between the builder tests and the find_program tests.
    # Use ``pytest`` when fixed
    - pytest -m "not fixsconsusage and not systemtest"
    - pytest -m "fixsconsusage"
    - cd ${test_root}
    # WAVES CLI regression tests
    - quickstart_regression_directory="${test_root}/test_quickstart"
    - waves quickstart ${quickstart_regression_directory}
    - cd ${quickstart_regression_directory}
    - scons . --jobs=4 --ignore-documentation
    - cd ${test_root}
    - waves visualize nominal --sconstruct ${quickstart_regression_directory}/SConstruct --output-file ${quickstart_regression_directory}/nominal.svg
    # Regression test the files used in the tutorial documentation
    - tutorials_regression_directory="${test_root}/test_tutorials"
    - waves fetch tutorials --destination ${tutorials_regression_directory}
    - cd ${tutorials_regression_directory}
    - scons . --sconstruct=scons_quickstart_SConstruct --keep-going
    - scons . --sconstruct=scons_multiactiontask_SConstruct --keep-going
    - cd waves_quickstart && scons rectangle --keep-going --unconditional-build && cd ..
    - scons . --sconstruct=tutorial_00_SConstruct --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_01_geometry_SConstruct --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_matlab_SConstruct --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_02_partition_mesh_SConstruct --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_argparse_types_SConstruct --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_03_solverprep_SConstruct --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_04_simulation_SConstruct --keep-going --unconditional-build
    # TODO: Figure out how to load the sierra module without breaking the CI tests. Change ``scons abaqus`` to ``scons .``
    # https://re-git.lanl.gov/aea/python-projects/waves/-/issues/515
    - cd tutorial_cubit && scons abaqus --keep-going --unconditional-build && cd ..
    - scons . --sconstruct=tutorial_escape_sequences_SConstruct --solve-cpus=1 --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_builder_post_actions_SConstruct --keep-going --unconditional-build
    # TODO: Figure out how to authenticate the institutional account without expanding the user credential exposure.
    # Until then, the SSH remote execution can't be integration/regression tested.
    #- scons . --sconstruct=tutorial_remote_execution_SConstruct --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_sbatch_SConstruct --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_05_parameter_substitution_SConstruct --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_06_include_files_SConstruct --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_07_cartesian_product_SConstruct --jobs=4 --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_07_latin_hypercube_SConstruct --jobs=4 --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_07_sobol_sequence_SConstruct --jobs=4 --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_08_data_extraction_SConstruct --jobs=4 --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_09_post_processing_SConstruct --jobs=4 --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_correlation_coefficients_SConstruct --jobs=4 --keep-going --unconditional-build
    - scons datacheck --sconstruct=tutorial_10_regression_testing_SConstruct --jobs=4 --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_11_archival_SConstruct --jobs=4 --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_task_reuse_SConstruct --jobs=4 --keep-going --unconditional-build
    - scons . --sconstruct=tutorial_mesh_convergence_SConstruct --jobs=4 --keep-going --unconditional-build
    - waves build --max-iterations=4 tutorial_extend_study --sconstruct=tutorial_extend_study_SConstruct --jobs=4
    - cd ${test_root}
