# Reference: https://github.com/softprops/action-gh-release
name: Release on new tags

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: 'true'
          fetch-depth: 0
      - name: Install latexmk
        run: sudo apt-get install -y texlive texlive-latex-extra latexmk
      - name: MiniConda setup
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: Conda environment
        shell: bash -el {0}
        run: conda install conda-build conda-verify 'scons>=4' 'setuptools>=45' 'setuptools_scm[toml]>=6.2' 'sphinx>=5.1' sphinx-argparse 'sphinx_rtd_theme>=1' sphinxcontrib-bibtex --yes --channel conda-forge
      - name: Build documentation
        shell: bash -el {0}
        run: scons latexpdf
      - name: Conda build
        shell: bash -el {0}
        run: VERSION=$(python -m setuptools_scm) conda build recipe --channel conda-forge --no-anaconda-upload --output-folder conda-build-artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/docs/latex/waves-${{ github.ref_name }}.pdf
            conda-build-artifacts/noarch/waves-${{ github.ref_name }}-py_0.tar.bz2
          body: "Changelog: https://lanl.github.io/waves/changelog.html. Installation: https://lanl.github.io/waves/installation.html"
